INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'hanh-trinh-nhin-lai-chinh-minh', 'post',
  'Hành trình nhìn lại chính mình trong một thế giới quá ồn',
  'Hành trình nhìn lại chính mình trong một thế giới quá ồn',
  'Looking back at yourself in an overly noisy world',
  'Có những giai đoạn con người không thiếu thông tin, mà thiếu một khoảng lặng đủ sâu để nhận ra mình đang đi về đâu và vì sao mình chọn con đường đó.',
  'Có những giai đoạn con người không thiếu thông tin, mà thiếu một khoảng lặng đủ sâu để nhận ra mình đang đi về đâu và vì sao mình chọn con đường đó.',
  'There are seasons when people do not lack information, but lack the stillness to notice where they are going and why they chose that direction.',
  '<p>Có những thời điểm con người sống giữa quá nhiều tín hiệu. Một tin nhắn chưa kịp trả lời, một mục tiêu mới vừa được người khác khoe ra, một xu hướng vừa xuất hiện, một nỗi sợ bị bỏ lại phía sau. Mỗi ngày đi qua giống như một dòng nước lớn cuốn ta về phía trước, nhưng không phải lúc nào phía trước cũng là nơi ta thật sự muốn đến.</p><p>Hành trình nhìn lại chính mình thường không bắt đầu bằng một biến cố lớn. Nó bắt đầu từ một câu hỏi nhỏ nhưng không còn né tránh được: mình đang sống đời sống này vì điều gì? Có người gặp câu hỏi đó khi công việc vẫn ổn nhưng lòng không còn sáng. Có người gặp nó giữa một mối quan hệ tưởng như đầy đủ nhưng lại thiếu sự thật.</p><p>Năm dấu hiệu cho thấy ta đang sống theo quán tính thường rất âm thầm. Ta luôn bận nhưng hiếm khi biết việc nào thật sự quan trọng. Ta ra quyết định chủ yếu vì sợ người khác thất vọng hoặc sợ mình bị tụt lại. Ta tiêu thụ rất nhiều nội dung nhưng ít có điều gì trở thành hiểu biết sống. Ta phản ứng nhanh với mọi chuyện nhưng ít khi dừng lại để nhìn nguyên nhân sâu hơn. Ta có thể kể rất rõ người khác đang làm gì, nhưng lại lúng túng khi nói điều mình thật sự cần.</p><p>Nhìn lại chính mình không phải là tự trách. Nó cũng không phải là rút khỏi cuộc đời để trở nên xa cách. Nhìn lại là khôi phục một năng lực rất căn bản: năng lực đứng về phía sự thật bên trong. Khi ta thấy mình đang mệt, ta không vội gọi đó là yếu đuối. Khi ta thấy mình đang ganh tị, ta không vội che giấu bằng đạo đức. Khi ta thấy mình đang lạc hướng, ta không vội tìm một công thức thành công mới.</p><p>Một đời sống có chiều sâu cần những khoảng lặng được bảo vệ. Có thể bắt đầu rất nhỏ: mười phút không điện thoại vào buổi sáng, một trang ghi chép trước khi ngủ, một cuộc trò chuyện thật lòng với người đáng tin, một buổi đi bộ không tai nghe. Điều quan trọng không nằm ở hình thức, mà ở việc ta thôi để mọi âm thanh bên ngoài chiếm toàn bộ không gian bên trong.</p><p>Đường Sao Tỏa Sáng xem việc nhìn lại chính mình như nền tảng của mọi hành trình phát triển. Không có sự thấy rõ, tri thức dễ biến thành trang trí. Không có sự thành thật, cộng đồng dễ biến thành đám đông. Không có một hướng đi bên trong, sáng tạo dễ trở thành cuộc chạy đua để được công nhận.</p><p>Nếu hôm nay bạn chỉ chọn một việc, hãy chọn một khoảng lặng đủ tử tế để hỏi: trong những điều mình đang theo đuổi, điều nào thật sự nuôi dưỡng mình, điều nào chỉ làm mình sợ bị bỏ lại?</p>',
  '<p>Có những thời điểm con người sống giữa quá nhiều tín hiệu. Một tin nhắn chưa kịp trả lời, một mục tiêu mới vừa được người khác khoe ra, một xu hướng vừa xuất hiện, một nỗi sợ bị bỏ lại phía sau. Mỗi ngày đi qua giống như một dòng nước lớn cuốn ta về phía trước, nhưng không phải lúc nào phía trước cũng là nơi ta thật sự muốn đến.</p><p>Hành trình nhìn lại chính mình thường không bắt đầu bằng một biến cố lớn. Nó bắt đầu từ một câu hỏi nhỏ nhưng không còn né tránh được: mình đang sống đời sống này vì điều gì? Có người gặp câu hỏi đó khi công việc vẫn ổn nhưng lòng không còn sáng. Có người gặp nó giữa một mối quan hệ tưởng như đầy đủ nhưng lại thiếu sự thật.</p><p>Năm dấu hiệu cho thấy ta đang sống theo quán tính thường rất âm thầm. Ta luôn bận nhưng hiếm khi biết việc nào thật sự quan trọng. Ta ra quyết định chủ yếu vì sợ người khác thất vọng hoặc sợ mình bị tụt lại. Ta tiêu thụ rất nhiều nội dung nhưng ít có điều gì trở thành hiểu biết sống. Ta phản ứng nhanh với mọi chuyện nhưng ít khi dừng lại để nhìn nguyên nhân sâu hơn. Ta có thể kể rất rõ người khác đang làm gì, nhưng lại lúng túng khi nói điều mình thật sự cần.</p><p>Nhìn lại chính mình không phải là tự trách. Nó cũng không phải là rút khỏi cuộc đời để trở nên xa cách. Nhìn lại là khôi phục một năng lực rất căn bản: năng lực đứng về phía sự thật bên trong. Khi ta thấy mình đang mệt, ta không vội gọi đó là yếu đuối. Khi ta thấy mình đang ganh tị, ta không vội che giấu bằng đạo đức. Khi ta thấy mình đang lạc hướng, ta không vội tìm một công thức thành công mới.</p><p>Một đời sống có chiều sâu cần những khoảng lặng được bảo vệ. Có thể bắt đầu rất nhỏ: mười phút không điện thoại vào buổi sáng, một trang ghi chép trước khi ngủ, một cuộc trò chuyện thật lòng với người đáng tin, một buổi đi bộ không tai nghe. Điều quan trọng không nằm ở hình thức, mà ở việc ta thôi để mọi âm thanh bên ngoài chiếm toàn bộ không gian bên trong.</p><p>Đường Sao Tỏa Sáng xem việc nhìn lại chính mình như nền tảng của mọi hành trình phát triển. Không có sự thấy rõ, tri thức dễ biến thành trang trí. Không có sự thành thật, cộng đồng dễ biến thành đám đông. Không có một hướng đi bên trong, sáng tạo dễ trở thành cuộc chạy đua để được công nhận.</p><p>Nếu hôm nay bạn chỉ chọn một việc, hãy chọn một khoảng lặng đủ tử tế để hỏi: trong những điều mình đang theo đuổi, điều nào thật sự nuôi dưỡng mình, điều nào chỉ làm mình sợ bị bỏ lại?</p>',
  '<p>There are seasons when people do not lack information, but lack the stillness to notice where they are going and why they chose that direction.</p><p>The journey of looking back at yourself rarely begins with a dramatic event. More often, it begins with a small question that can no longer be avoided: what am I living this life for? Some meet that question while work is stable but the heart feels dim. Some meet it inside a relationship that appears complete but lacks truth.</p><p>There are quiet signs that a person may be living on autopilot: constant busyness without clarity, decisions made from fear, endless content consumption without lived understanding, quick reactions without deeper seeing, and the ability to describe everyone else&#x27;s life while struggling to name one&#x27;s own need.</p><p>Looking back at yourself is not self-blame. It is the recovery of a basic capacity: standing with inner truth. A deep life needs protected silence. Ten phone-free minutes, one page of writing, one honest conversation, or one walk without headphones can become a doorway back to yourself.</p><p>Đường Sao Tỏa Sáng sees self-reflection as the ground of meaningful growth. Without clarity, knowledge becomes decoration. Without honesty, community becomes a crowd. Without inner direction, creativity becomes a race for recognition. Dare to ask what truly nourishes you and what merely keeps you afraid of being left behind.</p>',
  '', '', 'nhận thức,hành trình', 1,
  '2026-03-01T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'sang-tao-khong-bat-dau-tu-tham-vong', 'post',
  'Sáng tạo không bắt đầu từ tham vọng mà từ sự thấy rõ',
  'Sáng tạo không bắt đầu từ tham vọng mà từ sự thấy rõ',
  'Creativity does not begin with ambition but with clarity',
  'Điều tạo nên giá trị bền vững không phải là làm cho thật nhiều để được chú ý, mà là thấy đúng nhu cầu thật và tạo ra điều cần được sinh ra.',
  'Điều tạo nên giá trị bền vững không phải là làm cho thật nhiều để được chú ý, mà là thấy đúng nhu cầu thật và tạo ra điều cần được sinh ra.',
  'Lasting value does not come from producing more in order to be noticed, but from seeing a real need and bringing forth what truly deserves to exist.',
  '<p>Nhiều người bước vào sáng tạo với áp lực phải mới, phải lạ, phải khác, phải khiến người khác chú ý. Áp lực ấy có thể tạo ra tốc độ, nhưng không phải lúc nào tạo ra chiều sâu. Khi sáng tạo bị dẫn dắt bởi tham vọng được công nhận, ta dễ hỏi sai câu hỏi: làm sao để nổi bật hơn, thay vì điều gì đang thật sự cần được làm rõ.</p><p>Sáng tạo ở tầng sâu hơn bắt đầu từ sự thấy rõ. Thấy rõ một vấn đề chưa được gọi tên. Thấy rõ một nỗi đau mà nhiều người đang chịu nhưng chưa biết diễn đạt. Thấy rõ một khoảng trống trong đời sống mà sản phẩm, bài viết, chương trình hay cộng đồng có thể chạm đến một cách tử tế.</p><p>Một người viết có thể bắt đầu từ tham vọng trở thành người nổi tiếng. Nhưng nếu chỉ đi từ tham vọng đó, bài viết rất dễ trở thành tiếng ồn mới trong biển tiếng ồn cũ. Một người viết khác bắt đầu bằng việc lắng nghe: vì sao nhiều người trẻ đọc rất nhiều nhưng vẫn thấy rỗng? Vì sao họ thành công bên ngoài nhưng vẫn mệt bên trong? Vì sao họ có nhiều lựa chọn nhưng lại không biết chọn hướng nào?</p><p>Trong đời sống, nhu cầu thật thường không nằm trên bề mặt. Người ta nói cần động lực, nhưng có khi điều họ cần là được nghỉ mà không thấy tội lỗi. Người ta nói cần kỹ năng giao tiếp, nhưng có khi điều họ cần là can đảm nói thật mà không phá vỡ sự tôn trọng. Người ta nói cần thành công, nhưng có khi điều họ cần là một định nghĩa thành công không phản bội sức khỏe, gia đình và phẩm giá.</p><p>Điều này không phủ nhận tham vọng. Tham vọng có thể là năng lượng tốt nếu được đặt đúng chỗ. Nhưng tham vọng cần phục vụ sự thấy rõ, không thay thế sự thấy rõ. Khi tham vọng đứng trước, ta dễ ép cuộc đời phải chứng minh mình đặc biệt. Khi sự thấy rõ đứng trước, ta học cách để công việc phục vụ một giá trị lớn hơn sự khẳng định cá nhân.</p><p>Đường Sao Tỏa Sáng chọn đi theo hướng sáng tạo chậm và sâu. Một bài viết, một kịch bản, một sự kiện hay một chương trình không cần chỉ để lấp lịch đăng. Nó cần trả lời câu hỏi: điều này có giúp ai đó nhìn rõ hơn, sống thật hơn, đi tử tế hơn không?</p><p>Trước khi tạo ra điều tiếp theo, hãy thử dừng lại và hỏi: mình đang muốn được nhìn thấy, hay mình đang thật sự nhìn thấy một điều cần được chăm sóc?</p>',
  '<p>Nhiều người bước vào sáng tạo với áp lực phải mới, phải lạ, phải khác, phải khiến người khác chú ý. Áp lực ấy có thể tạo ra tốc độ, nhưng không phải lúc nào tạo ra chiều sâu. Khi sáng tạo bị dẫn dắt bởi tham vọng được công nhận, ta dễ hỏi sai câu hỏi: làm sao để nổi bật hơn, thay vì điều gì đang thật sự cần được làm rõ.</p><p>Sáng tạo ở tầng sâu hơn bắt đầu từ sự thấy rõ. Thấy rõ một vấn đề chưa được gọi tên. Thấy rõ một nỗi đau mà nhiều người đang chịu nhưng chưa biết diễn đạt. Thấy rõ một khoảng trống trong đời sống mà sản phẩm, bài viết, chương trình hay cộng đồng có thể chạm đến một cách tử tế.</p><p>Một người viết có thể bắt đầu từ tham vọng trở thành người nổi tiếng. Nhưng nếu chỉ đi từ tham vọng đó, bài viết rất dễ trở thành tiếng ồn mới trong biển tiếng ồn cũ. Một người viết khác bắt đầu bằng việc lắng nghe: vì sao nhiều người trẻ đọc rất nhiều nhưng vẫn thấy rỗng? Vì sao họ thành công bên ngoài nhưng vẫn mệt bên trong? Vì sao họ có nhiều lựa chọn nhưng lại không biết chọn hướng nào?</p><p>Trong đời sống, nhu cầu thật thường không nằm trên bề mặt. Người ta nói cần động lực, nhưng có khi điều họ cần là được nghỉ mà không thấy tội lỗi. Người ta nói cần kỹ năng giao tiếp, nhưng có khi điều họ cần là can đảm nói thật mà không phá vỡ sự tôn trọng. Người ta nói cần thành công, nhưng có khi điều họ cần là một định nghĩa thành công không phản bội sức khỏe, gia đình và phẩm giá.</p><p>Điều này không phủ nhận tham vọng. Tham vọng có thể là năng lượng tốt nếu được đặt đúng chỗ. Nhưng tham vọng cần phục vụ sự thấy rõ, không thay thế sự thấy rõ. Khi tham vọng đứng trước, ta dễ ép cuộc đời phải chứng minh mình đặc biệt. Khi sự thấy rõ đứng trước, ta học cách để công việc phục vụ một giá trị lớn hơn sự khẳng định cá nhân.</p><p>Đường Sao Tỏa Sáng chọn đi theo hướng sáng tạo chậm và sâu. Một bài viết, một kịch bản, một sự kiện hay một chương trình không cần chỉ để lấp lịch đăng. Nó cần trả lời câu hỏi: điều này có giúp ai đó nhìn rõ hơn, sống thật hơn, đi tử tế hơn không?</p><p>Trước khi tạo ra điều tiếp theo, hãy thử dừng lại và hỏi: mình đang muốn được nhìn thấy, hay mình đang thật sự nhìn thấy một điều cần được chăm sóc?</p>',
  '<p>Lasting value does not come from producing more in order to be noticed, but from seeing a real need and bringing forth what truly deserves to exist.</p><p>At a deeper level, creativity begins with clarity. It sees a problem that has not been named, a pain people carry but cannot express, a gap in daily life that content, community, or a program may touch with care. When clarity is present, creativity stops being a performance of the ego and becomes an act of response.</p><p>True needs are often not on the surface. People may ask for motivation when they need rest without guilt. They may ask for communication skills when they need courage to speak truth respectfully. They may ask for success when they need a definition of success that does not betray health, family, and dignity.</p><p>Ambition is not the enemy, but it must serve clarity rather than replace it. Đường Sao Tỏa Sáng chooses slow and deep creation: not content made to fill a schedule, but work that helps someone see more clearly, live more truthfully, and move more kindly.</p>',
  '', '', 'sáng tạo,nhận thức', 1,
  '2026-02-26T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'cong-dong-khong-phai-dam-dong', 'post',
  'Cộng đồng không phải đám đông, mà là những người cùng giữ một hướng đi',
  'Cộng đồng không phải đám đông, mà là những người cùng giữ một hướng đi',
  'Community is not a crowd, but people holding the same direction',
  'Một cộng đồng đúng không được xây bằng tiếng ồn hay số lượng, mà bằng sự tin cậy, trách nhiệm và khả năng cùng giữ một hướng đi đủ lâu.',
  'Một cộng đồng đúng không được xây bằng tiếng ồn hay số lượng, mà bằng sự tin cậy, trách nhiệm và khả năng cùng giữ một hướng đi đủ lâu.',
  'A true community is not built by noise or numbers, but by trust, responsibility, and the ability to hold a direction together over time.',
  '<p>Rất nhiều nơi tự gọi mình là cộng đồng chỉ vì có nhiều người xuất hiện cùng lúc. Có nhóm đông thành viên, nhiều tương tác, nhiều lời chào hỏi, nhiều hoạt động. Nhưng đông không tự động trở thành sâu. Một đám đông có thể cùng nhìn về một sân khấu trong vài giờ rồi tan đi mà không ai thật sự chịu trách nhiệm với ai.</p><p>Trong thời đại mạng xã hội, ta rất dễ nhầm sự náo nhiệt với sức sống. Một bài đăng nhiều phản ứng không chắc tạo ra kết nối. Một nhóm trò chuyện sôi nổi không chắc tạo ra tin cậy. Một phong trào bùng lên nhanh không chắc có khả năng đi xa. Nếu thiếu nền tảng, sự đông đúc có thể còn làm con người cô đơn hơn.</p><p>Một cộng đồng lành mạnh thường có ba tầng tin cậy. Tầng đầu tiên là sự an toàn: người tham gia biết mình có thể xuất hiện mà không bị chế giễu, khai thác hay phán xét vội vàng. Tầng thứ hai là trách nhiệm: mỗi người hiểu rằng tự do của mình đi cùng tác động lên người khác. Tầng thứ ba là hướng đi: dù khác biệt về hoàn cảnh, mọi người vẫn cùng tôn trọng một giá trị trung tâm.</p><p>Giá trị chung không cần phải là khẩu hiệu lớn. Nó có thể rất giản dị: nói thật hơn, đọc sâu hơn, sống tử tế hơn, sáng tạo có trách nhiệm hơn. Nhưng giá trị ấy phải được thực hành, không chỉ được treo lên như một tuyên bố. Một cộng đồng nói về lắng nghe nhưng không chịu nghe người yếu thế thì chưa thật sự có giá trị lắng nghe.</p><p>Cộng đồng cũng cần nhịp. Không phải lúc nào cũng phải sôi động. Có lúc cần gặp nhau, có lúc cần im lặng để mỗi người tiêu hóa điều đã học. Có lúc cần mở rộng, có lúc cần chậm lại để củng cố nền tảng. Một cộng đồng trưởng thành không sợ những khoảng trống.</p><p>Đường Sao Tỏa Sáng không xem cộng đồng như một tập hợp người theo dõi. Cộng đồng ở đây là những người cùng tập sống có ý thức hơn: đọc không chỉ để biết, nói không chỉ để thắng, làm không chỉ để chứng minh.</p><p>Khi bước vào bất kỳ cộng đồng nào, hãy thử hỏi: nơi này đang làm mình sâu hơn hay ồn hơn? Mình có được mời sống thật hơn không, hay chỉ được thúc đẩy thể hiện nhiều hơn?</p>',
  '<p>Rất nhiều nơi tự gọi mình là cộng đồng chỉ vì có nhiều người xuất hiện cùng lúc. Có nhóm đông thành viên, nhiều tương tác, nhiều lời chào hỏi, nhiều hoạt động. Nhưng đông không tự động trở thành sâu. Một đám đông có thể cùng nhìn về một sân khấu trong vài giờ rồi tan đi mà không ai thật sự chịu trách nhiệm với ai.</p><p>Trong thời đại mạng xã hội, ta rất dễ nhầm sự náo nhiệt với sức sống. Một bài đăng nhiều phản ứng không chắc tạo ra kết nối. Một nhóm trò chuyện sôi nổi không chắc tạo ra tin cậy. Một phong trào bùng lên nhanh không chắc có khả năng đi xa. Nếu thiếu nền tảng, sự đông đúc có thể còn làm con người cô đơn hơn.</p><p>Một cộng đồng lành mạnh thường có ba tầng tin cậy. Tầng đầu tiên là sự an toàn: người tham gia biết mình có thể xuất hiện mà không bị chế giễu, khai thác hay phán xét vội vàng. Tầng thứ hai là trách nhiệm: mỗi người hiểu rằng tự do của mình đi cùng tác động lên người khác. Tầng thứ ba là hướng đi: dù khác biệt về hoàn cảnh, mọi người vẫn cùng tôn trọng một giá trị trung tâm.</p><p>Giá trị chung không cần phải là khẩu hiệu lớn. Nó có thể rất giản dị: nói thật hơn, đọc sâu hơn, sống tử tế hơn, sáng tạo có trách nhiệm hơn. Nhưng giá trị ấy phải được thực hành, không chỉ được treo lên như một tuyên bố. Một cộng đồng nói về lắng nghe nhưng không chịu nghe người yếu thế thì chưa thật sự có giá trị lắng nghe.</p><p>Cộng đồng cũng cần nhịp. Không phải lúc nào cũng phải sôi động. Có lúc cần gặp nhau, có lúc cần im lặng để mỗi người tiêu hóa điều đã học. Có lúc cần mở rộng, có lúc cần chậm lại để củng cố nền tảng. Một cộng đồng trưởng thành không sợ những khoảng trống.</p><p>Đường Sao Tỏa Sáng không xem cộng đồng như một tập hợp người theo dõi. Cộng đồng ở đây là những người cùng tập sống có ý thức hơn: đọc không chỉ để biết, nói không chỉ để thắng, làm không chỉ để chứng minh.</p><p>Khi bước vào bất kỳ cộng đồng nào, hãy thử hỏi: nơi này đang làm mình sâu hơn hay ồn hơn? Mình có được mời sống thật hơn không, hay chỉ được thúc đẩy thể hiện nhiều hơn?</p>',
  '<p>A true community is not built by noise or numbers, but by trust, responsibility, and the ability to hold a direction together over time.</p><p>Many spaces call themselves communities because many people gather there. But numbers do not automatically become depth. A crowd may face the same stage for a few hours and disappear without responsibility. A community begins when people share a value clear enough to protect together.</p><p>A healthy community has layers of trust: safety, responsibility, and direction. People can show up without being mocked; they understand their freedom affects others; and they honor a central value even when backgrounds differ.</p><p>Đường Sao Tỏa Sáng does not see community as a collection of followers. It is a practice of living more consciously: reading not only to know, speaking not only to win, doing not only to prove. A true community helps you return to yourself with the support of people moving in the same direction.</p>',
  '', '', 'cộng đồng', 1,
  '2026-02-20T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'mot-doi-song-khong-bi-pha-tan-boi-xa-hoi', 'post',
  'Một đời sống không bị phân tán bởi xã hội cần được xây thế nào',
  'Một đời sống không bị phân tán bởi xã hội cần được xây thế nào',
  'How to build a life not scattered by society',
  'Khi không tự thiết kế đời sống của mình, con người rất dễ bị kéo vào chương trình của người khác và tưởng đó là lựa chọn của chính mình.',
  'Khi không tự thiết kế đời sống của mình, con người rất dễ bị kéo vào chương trình của người khác và tưởng đó là lựa chọn của chính mình.',
  'When you do not design your own life, you are easily pulled into someone else''s program and may mistake it for your own choice.',
  '<p>Cuộc sống hiện đại đầy những lời mời gọi: làm nhiều hơn, kiếm nhiều hơn, cập nhật nhiều hơn, phản hồi nhanh hơn, hiện diện ở nhiều nơi hơn. Mỗi lời mời có vẻ hợp lý khi đứng một mình. Nhưng khi cộng lại, chúng có thể biến đời sống thành một mảnh vải bị kéo từ quá nhiều phía.</p><p>Một đời sống bị phân tán không nhất thiết là đời sống thất bại. Nó có thể trông rất thành công: lịch kín, quan hệ rộng, mục tiêu rõ, thành tích có thật. Vấn đề nằm ở chỗ năng lượng bên trong bị chia nhỏ đến mức ta không còn biết điều gì là trung tâm. Khi không có trung tâm, mỗi cơ hội mới đều có vẻ quan trọng.</p><p>Thiết kế đời sống không có nghĩa là kiểm soát mọi thứ. Thiết kế đời sống là xác định những trục không được đánh mất. Trục thứ nhất là sức khỏe thân tâm. Trục thứ hai là giá trị. Trục thứ ba là quan hệ nền tảng. Nếu một lựa chọn buộc ta đánh đổi cả ba trục này, lựa chọn ấy cần được nhìn lại.</p><p>Một khung đơn giản để bắt đầu là chia đời sống thành ba vòng. Vòng lõi là những điều không thương lượng: sức khỏe, phẩm giá, sự thật, người thân thiết, việc học sâu. Vòng phát triển là những điều giúp ta mở rộng: công việc, dự án, kỹ năng, cộng đồng, tài chính. Vòng nhiễu là những điều tiêu hao nhiều hơn nuôi dưỡng: so sánh, phản ứng tức thời, tiêu thụ vô thức, nhu cầu chứng minh.</p><p>Xã hội không xấu vì có nhiều lựa chọn. Vấn đề là ta bước vào những lựa chọn đó mà không có tiêu chuẩn bên trong. Một người có tiêu chuẩn sẽ biết từ chối mà không cần ghét bỏ, biết chậm lại mà không thấy mình thua, biết làm ít hơn ở một số việc để làm sâu hơn ở điều quan trọng.</p><p>Đường Sao Tỏa Sáng đề xuất một cách sống có chủ ý: không chạy trốn xã hội, nhưng cũng không để xã hội thiết kế toàn bộ nội tâm mình. Ta vẫn làm việc, sáng tạo, kết nối và đóng góp. Nhưng ta làm từ một trung tâm rõ hơn.</p><p>Hãy nhìn lại tuần vừa qua: điều gì đã nuôi dưỡng bạn, điều gì chỉ kéo bạn đi? Nếu phải giữ lại ba điều làm nên phẩm chất đời sống của mình, bạn sẽ giữ điều gì?</p>',
  '<p>Cuộc sống hiện đại đầy những lời mời gọi: làm nhiều hơn, kiếm nhiều hơn, cập nhật nhiều hơn, phản hồi nhanh hơn, hiện diện ở nhiều nơi hơn. Mỗi lời mời có vẻ hợp lý khi đứng một mình. Nhưng khi cộng lại, chúng có thể biến đời sống thành một mảnh vải bị kéo từ quá nhiều phía.</p><p>Một đời sống bị phân tán không nhất thiết là đời sống thất bại. Nó có thể trông rất thành công: lịch kín, quan hệ rộng, mục tiêu rõ, thành tích có thật. Vấn đề nằm ở chỗ năng lượng bên trong bị chia nhỏ đến mức ta không còn biết điều gì là trung tâm. Khi không có trung tâm, mỗi cơ hội mới đều có vẻ quan trọng.</p><p>Thiết kế đời sống không có nghĩa là kiểm soát mọi thứ. Thiết kế đời sống là xác định những trục không được đánh mất. Trục thứ nhất là sức khỏe thân tâm. Trục thứ hai là giá trị. Trục thứ ba là quan hệ nền tảng. Nếu một lựa chọn buộc ta đánh đổi cả ba trục này, lựa chọn ấy cần được nhìn lại.</p><p>Một khung đơn giản để bắt đầu là chia đời sống thành ba vòng. Vòng lõi là những điều không thương lượng: sức khỏe, phẩm giá, sự thật, người thân thiết, việc học sâu. Vòng phát triển là những điều giúp ta mở rộng: công việc, dự án, kỹ năng, cộng đồng, tài chính. Vòng nhiễu là những điều tiêu hao nhiều hơn nuôi dưỡng: so sánh, phản ứng tức thời, tiêu thụ vô thức, nhu cầu chứng minh.</p><p>Xã hội không xấu vì có nhiều lựa chọn. Vấn đề là ta bước vào những lựa chọn đó mà không có tiêu chuẩn bên trong. Một người có tiêu chuẩn sẽ biết từ chối mà không cần ghét bỏ, biết chậm lại mà không thấy mình thua, biết làm ít hơn ở một số việc để làm sâu hơn ở điều quan trọng.</p><p>Đường Sao Tỏa Sáng đề xuất một cách sống có chủ ý: không chạy trốn xã hội, nhưng cũng không để xã hội thiết kế toàn bộ nội tâm mình. Ta vẫn làm việc, sáng tạo, kết nối và đóng góp. Nhưng ta làm từ một trung tâm rõ hơn.</p><p>Hãy nhìn lại tuần vừa qua: điều gì đã nuôi dưỡng bạn, điều gì chỉ kéo bạn đi? Nếu phải giữ lại ba điều làm nên phẩm chất đời sống của mình, bạn sẽ giữ điều gì?</p>',
  '<p>When you do not design your own life, you are easily pulled into someone else&#x27;s program and may mistake it for your own choice.</p><p>A scattered life can look successful: a full schedule, wide connections, clear goals, real achievements. The problem is that inner energy becomes divided until nothing feels central. Without a center, every opportunity appears urgent and every trend seems necessary.</p><p>Designing a life means naming the axes that must not be lost: health, values, and foundational relationships. A simple practice is to divide life into three circles: the core that must be protected, the growth that helps you expand, and the noise that consumes more than it nourishes.</p><p>Đường Sao Tỏa Sáng proposes intentional living: do not escape society, but do not allow society to design your entire inner life. Work, create, connect, and contribute from a clearer center.</p>',
  '', '', 'nhận thức,định hướng', 1,
  '2026-02-14T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'doc-cham-de-song-sau', 'post',
  'Đọc chậm để sống sâu hơn trong thời đại đọc lướt',
  'Đọc chậm để sống sâu hơn trong thời đại đọc lướt',
  'Read slowly to live more deeply in an age of skimming',
  'Một bài viết tốt không chỉ cung cấp thông tin, mà mở ra một không gian để người đọc dừng lại, soi chiếu và gặp lại chính mình.',
  'Một bài viết tốt không chỉ cung cấp thông tin, mà mở ra một không gian để người đọc dừng lại, soi chiếu và gặp lại chính mình.',
  'A strong piece of writing does not only provide information; it opens a space where the reader can pause, reflect, and meet themselves again.',
  '<p>Trong thời đại mà mọi thứ được tối ưu cho tốc độ, việc đọc cũng bị cuốn vào nhịp lướt. Ta lướt tiêu đề, lướt đoạn mở đầu, lướt vài câu nổi bật rồi chuyển sang nội dung tiếp theo. Cách đọc ấy giúp ta thu nhận nhiều tín hiệu, nhưng không chắc giúp ta hiểu sâu hơn.</p><p>Đọc chậm không phải là hoài niệm về một thời xưa cũ. Nó là một năng lực sống cần được phục hồi. Khi đọc chậm, ta không chỉ hỏi bài viết này nói gì, mà còn hỏi nó đang chạm vào phần nào trong đời sống của mình. Ta để một câu ở lại lâu hơn. Ta cho phép một ý làm mình khó chịu.</p><p>Phương pháp đọc chậm có thể bắt đầu bằng bốn bước. Bước một là dừng: trước khi đọc, đặt điện thoại ở xa hơn một chút, thở chậm và cho mình biết đây không phải cuộc đua. Bước hai là đọc thành lớp: lần đầu đọc để nắm mạch, lần sau đọc để tìm ý chính, lần nữa đọc để nhận ra điều liên quan đến mình. Bước ba là ghi lại một câu khiến mình dừng lại. Bước bốn là đem câu đó vào đời sống bằng một hành động nhỏ.</p><p>Một bài viết sâu không cần làm người đọc choáng ngợp. Nó cần đủ thật để mở ra một cuộc đối thoại. Có những đoạn không đưa ra lời khuyên trực tiếp, nhưng khiến ta thấy rõ một thói quen cũ. Có những câu không giải quyết vấn đề ngay, nhưng giúp ta gọi đúng tên vấn đề.</p><p>Đọc chậm cũng là một cách bảo vệ tự do nội tâm. Khi ta chỉ lướt, thuật toán dễ quyết định điều gì được chú ý. Khi ta đọc chậm, ta lấy lại quyền chọn điều gì xứng đáng ở lại trong mình. Ta học phân biệt giữa thứ kích thích nhất thời và thứ nuôi dưỡng lâu dài.</p><p>Đường Sao Tỏa Sáng được xây trên tinh thần đọc chậm để sống sâu. Nội dung không chỉ để được tiêu thụ, mà để được đi cùng. Một bài viết có thể là điểm hẹn cho một buổi tối yên tĩnh, một cuộc trò chuyện, một trang nhật ký, hoặc một quyết định nhỏ nhưng thật.</p><p>Lần tới khi gặp một bài viết chạm vào mình, đừng vội chia sẻ ngay. Hãy ở lại với nó thêm vài phút. Hỏi xem điều gì trong mình vừa được đánh thức.</p>',
  '<p>Trong thời đại mà mọi thứ được tối ưu cho tốc độ, việc đọc cũng bị cuốn vào nhịp lướt. Ta lướt tiêu đề, lướt đoạn mở đầu, lướt vài câu nổi bật rồi chuyển sang nội dung tiếp theo. Cách đọc ấy giúp ta thu nhận nhiều tín hiệu, nhưng không chắc giúp ta hiểu sâu hơn.</p><p>Đọc chậm không phải là hoài niệm về một thời xưa cũ. Nó là một năng lực sống cần được phục hồi. Khi đọc chậm, ta không chỉ hỏi bài viết này nói gì, mà còn hỏi nó đang chạm vào phần nào trong đời sống của mình. Ta để một câu ở lại lâu hơn. Ta cho phép một ý làm mình khó chịu.</p><p>Phương pháp đọc chậm có thể bắt đầu bằng bốn bước. Bước một là dừng: trước khi đọc, đặt điện thoại ở xa hơn một chút, thở chậm và cho mình biết đây không phải cuộc đua. Bước hai là đọc thành lớp: lần đầu đọc để nắm mạch, lần sau đọc để tìm ý chính, lần nữa đọc để nhận ra điều liên quan đến mình. Bước ba là ghi lại một câu khiến mình dừng lại. Bước bốn là đem câu đó vào đời sống bằng một hành động nhỏ.</p><p>Một bài viết sâu không cần làm người đọc choáng ngợp. Nó cần đủ thật để mở ra một cuộc đối thoại. Có những đoạn không đưa ra lời khuyên trực tiếp, nhưng khiến ta thấy rõ một thói quen cũ. Có những câu không giải quyết vấn đề ngay, nhưng giúp ta gọi đúng tên vấn đề.</p><p>Đọc chậm cũng là một cách bảo vệ tự do nội tâm. Khi ta chỉ lướt, thuật toán dễ quyết định điều gì được chú ý. Khi ta đọc chậm, ta lấy lại quyền chọn điều gì xứng đáng ở lại trong mình. Ta học phân biệt giữa thứ kích thích nhất thời và thứ nuôi dưỡng lâu dài.</p><p>Đường Sao Tỏa Sáng được xây trên tinh thần đọc chậm để sống sâu. Nội dung không chỉ để được tiêu thụ, mà để được đi cùng. Một bài viết có thể là điểm hẹn cho một buổi tối yên tĩnh, một cuộc trò chuyện, một trang nhật ký, hoặc một quyết định nhỏ nhưng thật.</p><p>Lần tới khi gặp một bài viết chạm vào mình, đừng vội chia sẻ ngay. Hãy ở lại với nó thêm vài phút. Hỏi xem điều gì trong mình vừa được đánh thức.</p>',
  '<p>A strong piece of writing does not only provide information; it opens a space where the reader can pause, reflect, and meet themselves again.</p><p>Slow reading is not nostalgia. It is a life capacity that needs to be recovered. When we read slowly, we do not only ask what the article says; we ask what part of our life it touches. We let a sentence stay. We notice where we agree too quickly or resist too strongly.</p><p>A slow reading practice can begin with four steps: pause, read in layers, write down one sentence that stops you, and carry that sentence into the day through one small action.</p><p>Đường Sao Tỏa Sáng is built on the spirit of reading slowly in order to live more deeply. Content is not only to be consumed; it is to be accompanied. Depth may come not from reading ten more articles, but from allowing one article to travel its full distance through your life.</p>',
  '', '', 'hành trình,nhận thức', 1,
  '2026-02-10T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'khoi-nghiep-tu-noi-song-that', 'post',
  'Khởi nghiệp từ nơi sống thật thay vì từ nỗi sợ phải chứng minh',
  'Khởi nghiệp từ nơi sống thật thay vì từ nỗi sợ phải chứng minh',
  'Building from real living instead of the fear of proving yourself',
  'Nếu bắt đầu chỉ để chứng minh mình hơn người khác, ta sẽ rất nhanh kiệt sức trước khi đi đến giá trị thật mà dự án có thể trao cho đời sống.',
  'Nếu bắt đầu chỉ để chứng minh mình hơn người khác, ta sẽ rất nhanh kiệt sức trước khi đi đến giá trị thật mà dự án có thể trao cho đời sống.',
  'If you begin only to prove yourself against others, exhaustion often arrives before the project reaches the real value it could offer life.',
  '<p>Nhiều dự án khởi đầu rất mạnh vì được đẩy bằng năng lượng chứng minh. Chứng minh rằng mình giỏi, mình khác, mình không thua, mình có thể làm điều lớn. Năng lượng ấy có thể giúp một người thức khuya, làm nhanh, vượt qua sự nghi ngờ ban đầu. Nhưng nếu nó là nền móng duy nhất, dự án sẽ mang trong mình một sự căng thẳng khó giấu.</p><p>Khởi nghiệp từ nỗi sợ thường tạo ra những cấu trúc lệch. Ta chọn sản phẩm vì thị trường đang khen, không phải vì mình hiểu vấn đề. Ta chọn tốc độ vì sợ bị bỏ lại, không phải vì người dùng cần như vậy. Ta chọn hình ảnh vì muốn được công nhận, không phải vì nó phản ánh giá trị thật.</p><p>Khởi nghiệp từ nơi sống thật không có nghĩa là mơ mộng, thiếu thực tế hay bỏ qua tài chính. Ngược lại, nó đòi hỏi sự thực tế sâu hơn. Sống thật là biết mình đang giải quyết vấn đề nào, cho ai, vì sao vấn đề đó đáng được giải quyết, và mình có sẵn sàng chăm sóc nó khi không còn hào quang ban đầu hay không.</p><p>Có một khác biệt lớn giữa khởi nghiệp từ giá trị và khởi nghiệp từ nỗi sợ. Khi đi từ nỗi sợ, mỗi phản hồi tiêu cực giống như một lời phủ định con người mình. Khi đi từ giá trị, phản hồi là dữ liệu để làm rõ hơn cách phục vụ. Khi đi từ nỗi sợ, thành công của người khác trở thành mối đe dọa. Khi đi từ giá trị, thành công của người khác có thể là thông tin, cảm hứng hoặc lời nhắc rằng còn nhiều cách đóng góp.</p><p>Điều này đặc biệt quan trọng với những dự án liên quan đến nội dung, giáo dục, cộng đồng và chuyển hóa con người. Nếu người làm dự án không thành thật với động cơ của mình, họ rất dễ dùng ngôn ngữ đẹp để che một nhu cầu được tôn sùng.</p><p>Đường Sao Tỏa Sáng chọn xây từ nơi sống thật: chậm hơn nếu cần, nhỏ hơn nếu cần, nhưng rõ hơn về giá trị. Việc khởi tạo một nền tảng không chỉ là dựng trang, viết bài, mở kênh hay tổ chức hoạt động. Đó là quá trình kiểm tra liên tục: điều này có trung thực với lời mời ban đầu không?</p><p>Nếu bạn đang bắt đầu một điều gì đó, hãy hỏi: mình đang xây để phục vụ điều gì, hay để thoát khỏi cảm giác mình chưa đủ?</p>',
  '<p>Nhiều dự án khởi đầu rất mạnh vì được đẩy bằng năng lượng chứng minh. Chứng minh rằng mình giỏi, mình khác, mình không thua, mình có thể làm điều lớn. Năng lượng ấy có thể giúp một người thức khuya, làm nhanh, vượt qua sự nghi ngờ ban đầu. Nhưng nếu nó là nền móng duy nhất, dự án sẽ mang trong mình một sự căng thẳng khó giấu.</p><p>Khởi nghiệp từ nỗi sợ thường tạo ra những cấu trúc lệch. Ta chọn sản phẩm vì thị trường đang khen, không phải vì mình hiểu vấn đề. Ta chọn tốc độ vì sợ bị bỏ lại, không phải vì người dùng cần như vậy. Ta chọn hình ảnh vì muốn được công nhận, không phải vì nó phản ánh giá trị thật.</p><p>Khởi nghiệp từ nơi sống thật không có nghĩa là mơ mộng, thiếu thực tế hay bỏ qua tài chính. Ngược lại, nó đòi hỏi sự thực tế sâu hơn. Sống thật là biết mình đang giải quyết vấn đề nào, cho ai, vì sao vấn đề đó đáng được giải quyết, và mình có sẵn sàng chăm sóc nó khi không còn hào quang ban đầu hay không.</p><p>Có một khác biệt lớn giữa khởi nghiệp từ giá trị và khởi nghiệp từ nỗi sợ. Khi đi từ nỗi sợ, mỗi phản hồi tiêu cực giống như một lời phủ định con người mình. Khi đi từ giá trị, phản hồi là dữ liệu để làm rõ hơn cách phục vụ. Khi đi từ nỗi sợ, thành công của người khác trở thành mối đe dọa. Khi đi từ giá trị, thành công của người khác có thể là thông tin, cảm hứng hoặc lời nhắc rằng còn nhiều cách đóng góp.</p><p>Điều này đặc biệt quan trọng với những dự án liên quan đến nội dung, giáo dục, cộng đồng và chuyển hóa con người. Nếu người làm dự án không thành thật với động cơ của mình, họ rất dễ dùng ngôn ngữ đẹp để che một nhu cầu được tôn sùng.</p><p>Đường Sao Tỏa Sáng chọn xây từ nơi sống thật: chậm hơn nếu cần, nhỏ hơn nếu cần, nhưng rõ hơn về giá trị. Việc khởi tạo một nền tảng không chỉ là dựng trang, viết bài, mở kênh hay tổ chức hoạt động. Đó là quá trình kiểm tra liên tục: điều này có trung thực với lời mời ban đầu không?</p><p>Nếu bạn đang bắt đầu một điều gì đó, hãy hỏi: mình đang xây để phục vụ điều gì, hay để thoát khỏi cảm giác mình chưa đủ?</p>',
  '<p>If you begin only to prove yourself against others, exhaustion often arrives before the project reaches the real value it could offer life.</p><p>Many ventures begin with the need to prove: that I am capable, different, not behind, able to build something significant. This energy can create speed, but if it becomes the only foundation, the project must keep winning for its creator to feel worthy.</p><p>Building from real living does not mean being impractical. It means knowing what problem you are solving, for whom, why it deserves care, and whether you can continue caring after the first glow fades.</p><p>Đường Sao Tỏa Sáng chooses to build from real living: slower if necessary, smaller if necessary, but clearer in value. The question is not only whether something can grow, but whether it remains faithful to the original invitation.</p>',
  '', '', 'sáng tạo,hành trình', 1,
  '2026-02-06T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'vi-sao-con-nguoi-mat-phuong-huong', 'post',
  'Vì sao con người mất phương hướng dù có quá nhiều lựa chọn',
  'Vì sao con người mất phương hướng dù có quá nhiều lựa chọn',
  'Why people lose direction even with too many choices',
  'Sự phong phú bên ngoài không thể thay thế cho một la bàn bên trong; nếu thiếu hướng đi, lựa chọn càng nhiều càng dễ làm con người kiệt sức.',
  'Sự phong phú bên ngoài không thể thay thế cho một la bàn bên trong; nếu thiếu hướng đi, lựa chọn càng nhiều càng dễ làm con người kiệt sức.',
  'Outer abundance cannot replace an inner compass; without direction, more choices often make people more exhausted.',
  '<p>Nghịch lý của thời đại hiện nay là con người có nhiều lựa chọn hơn bao giờ hết nhưng lại mất phương hướng nhiều hơn bao giờ hết. Ta có thể học bất cứ kỹ năng nào, theo dõi bất cứ lối sống nào, thử nhiều con đường nghề nghiệp, kết nối với nhiều nhóm người, tiếp cận vô số tri thức. Nhưng chính sự phong phú đó đôi khi không mở rộng tự do, mà làm tâm trí nặng hơn.</p><p>Mất phương hướng không chỉ là không biết làm nghề gì hay sống ở đâu. Sâu hơn, đó là trạng thái không còn cảm nhận được tiêu chuẩn bên trong. Ta chọn vì người khác chọn. Ta đổi hướng vì thấy người khác thành công. Ta nghi ngờ chính mình mỗi khi gặp một câu chuyện truyền cảm hứng mới.</p><p>Một bản đồ phương hướng nội tâm cần ít nhất bốn điểm. Điểm thứ nhất là giá trị: điều gì nếu đánh mất sẽ khiến ta không còn tôn trọng chính mình? Điểm thứ hai là năng lượng: hoạt động nào làm ta mệt nhưng vẫn thấy có ý nghĩa, và hoạt động nào làm ta mệt theo kiểu rỗng? Điểm thứ ba là trách nhiệm: ai và điều gì đang thật sự cần sự hiện diện của ta? Điểm thứ tư là giới hạn: cái gì không còn phù hợp, dù từng rất quan trọng trong một giai đoạn cũ?</p><p>Khi thiếu bản đồ này, lựa chọn trở thành gánh nặng. Một cơ hội mới không còn là cơ hội, mà là thêm một điều phải cân nhắc. Một lời khuyên tốt không còn giúp đỡ, mà tạo thêm áp lực. Một câu chuyện thành công không còn truyền cảm hứng, mà làm ta thấy mình chậm.</p><p>Để tìm lại hướng đi, đôi khi không cần thêm thông tin. Cần bớt nhiễu. Bớt so sánh trong một khoảng thời gian. Bớt hỏi người khác mình nên trở thành ai. Bớt tiêu thụ những câu chuyện khiến mình liên tục thấy thiếu.</p><p>Đường Sao Tỏa Sáng không hứa trao cho ai một đáp án có sẵn. Một hướng đi thật không thể được áp từ bên ngoài. Điều nền tảng có thể làm là tạo không gian, câu hỏi và chất liệu để mỗi người nghe lại la bàn của mình.</p><p>Nếu bạn đang đứng giữa quá nhiều lựa chọn, hãy tạm hỏi ít hơn rằng lựa chọn nào tốt nhất theo xã hội. Hãy hỏi lựa chọn nào giúp bạn sống gần hơn với giá trị, năng lượng, trách nhiệm và giới hạn thật của mình.</p>',
  '<p>Nghịch lý của thời đại hiện nay là con người có nhiều lựa chọn hơn bao giờ hết nhưng lại mất phương hướng nhiều hơn bao giờ hết. Ta có thể học bất cứ kỹ năng nào, theo dõi bất cứ lối sống nào, thử nhiều con đường nghề nghiệp, kết nối với nhiều nhóm người, tiếp cận vô số tri thức. Nhưng chính sự phong phú đó đôi khi không mở rộng tự do, mà làm tâm trí nặng hơn.</p><p>Mất phương hướng không chỉ là không biết làm nghề gì hay sống ở đâu. Sâu hơn, đó là trạng thái không còn cảm nhận được tiêu chuẩn bên trong. Ta chọn vì người khác chọn. Ta đổi hướng vì thấy người khác thành công. Ta nghi ngờ chính mình mỗi khi gặp một câu chuyện truyền cảm hứng mới.</p><p>Một bản đồ phương hướng nội tâm cần ít nhất bốn điểm. Điểm thứ nhất là giá trị: điều gì nếu đánh mất sẽ khiến ta không còn tôn trọng chính mình? Điểm thứ hai là năng lượng: hoạt động nào làm ta mệt nhưng vẫn thấy có ý nghĩa, và hoạt động nào làm ta mệt theo kiểu rỗng? Điểm thứ ba là trách nhiệm: ai và điều gì đang thật sự cần sự hiện diện của ta? Điểm thứ tư là giới hạn: cái gì không còn phù hợp, dù từng rất quan trọng trong một giai đoạn cũ?</p><p>Khi thiếu bản đồ này, lựa chọn trở thành gánh nặng. Một cơ hội mới không còn là cơ hội, mà là thêm một điều phải cân nhắc. Một lời khuyên tốt không còn giúp đỡ, mà tạo thêm áp lực. Một câu chuyện thành công không còn truyền cảm hứng, mà làm ta thấy mình chậm.</p><p>Để tìm lại hướng đi, đôi khi không cần thêm thông tin. Cần bớt nhiễu. Bớt so sánh trong một khoảng thời gian. Bớt hỏi người khác mình nên trở thành ai. Bớt tiêu thụ những câu chuyện khiến mình liên tục thấy thiếu.</p><p>Đường Sao Tỏa Sáng không hứa trao cho ai một đáp án có sẵn. Một hướng đi thật không thể được áp từ bên ngoài. Điều nền tảng có thể làm là tạo không gian, câu hỏi và chất liệu để mỗi người nghe lại la bàn của mình.</p><p>Nếu bạn đang đứng giữa quá nhiều lựa chọn, hãy tạm hỏi ít hơn rằng lựa chọn nào tốt nhất theo xã hội. Hãy hỏi lựa chọn nào giúp bạn sống gần hơn với giá trị, năng lượng, trách nhiệm và giới hạn thật của mình.</p>',
  '<p>Outer abundance cannot replace an inner compass; without direction, more choices often make people more exhausted.</p><p>Being directionless is not only about not knowing what job to take or where to live. At a deeper level, it is the loss of an inner standard. We choose because others choose, change direction because someone else appears successful, and doubt ourselves whenever a new inspiring story appears.</p><p>An inner map needs values, energy, responsibility, and limits. Without that map, choice becomes a burden. To find direction again, we may not need more information. We may need less noise.</p><p>Đường Sao Tỏa Sáng cannot impose a ready-made answer. It can create space and questions for each person to hear their own compass again. Direction may simply be the next step that does not betray what is deepest in you.</p>',
  '', '', 'nhận thức', 1,
  '2026-01-28T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);

INSERT OR REPLACE INTO contents (
  slug, type,
  title, title_vi, title_en,
  excerpt, excerpt_vi, excerpt_en,
  content, content_vi, content_en,
  cover, cover_url, tags, published,
  created_at, updated_at
) VALUES (
  'duong-di-cua-nhung-nguoi-muon-song-khac', 'post',
  'Đường đi của những người muốn sống khác nhưng chưa biết bắt đầu từ đâu',
  'Đường đi của những người muốn sống khác nhưng chưa biết bắt đầu từ đâu',
  'The path for those who want to live differently but do not know where to begin',
  'Điểm bắt đầu không nằm ở việc đổi hết mọi thứ ngay lập tức, mà ở việc nhìn ra điều cần giữ, điều cần dừng và bước nhỏ nào đủ thật để đi hôm nay.',
  'Điểm bắt đầu không nằm ở việc đổi hết mọi thứ ngay lập tức, mà ở việc nhìn ra điều cần giữ, điều cần dừng và bước nhỏ nào đủ thật để đi hôm nay.',
  'The beginning is not changing everything at once, but seeing what must be kept, what must stop, and what small truthful step can be taken today.',
  '<p>Có rất nhiều người cảm thấy đời sống hiện tại không còn phù hợp với mình nữa. Họ vẫn làm những việc cần làm, vẫn giữ những vai trò quen thuộc, vẫn mỉm cười trong những cuộc gặp thường ngày. Nhưng bên trong có một cảm giác lặng lẽ rằng nếu cứ sống như cũ thêm nhiều năm nữa, điều gì đó quan trọng sẽ bị đánh mất.</p><p>Muốn sống khác không có nghĩa là ghét đời sống hiện tại. Nhiều khi đó là dấu hiệu của sự trưởng thành. Một phiên bản cũ từng giúp ta đi qua một giai đoạn, nhưng không nhất thiết đủ cho giai đoạn tiếp theo. Một công việc từng nuôi sống ta, một mối quan hệ từng nâng đỡ ta, một cách nghĩ từng bảo vệ ta, đến lúc nào đó có thể cần được nhìn lại.</p><p>Chân dung của người muốn sống khác thường không phải người bốc đồng. Họ có thể rất trách nhiệm, thậm chí quá trách nhiệm. Họ không muốn phá bỏ mọi thứ chỉ để thỏa mãn cảm xúc nhất thời. Họ chỉ cảm thấy cần một đời sống thật hơn: làm việc không phản bội giá trị, kết nối không đánh mất lòng tự trọng, phát triển không làm cạn kiệt sức khỏe, thành công không khiến mình xa lạ với chính mình.</p><p>Điểm bắt đầu thường không phải là đổi hết mọi thứ. Nó là phân biệt ba nhóm điều. Nhóm thứ nhất là điều cần giữ: những giá trị, con người, thói quen và trách nhiệm vẫn còn nuôi dưỡng mình. Nhóm thứ hai là điều cần dừng: những vòng lặp làm mình nhỏ lại, những cam kết không còn thật, những cách sống chỉ nhằm tránh sự phán xét. Nhóm thứ ba là điều cần thử: một thực hành nhỏ, một cuộc trò chuyện thật, một khoảng nghỉ, một dự án phụ, một cách học mới để kiểm chứng hướng đi.</p><p>Sống khác cần can đảm, nhưng cũng cần sự hiền lành với chính mình. Nếu quá vội, ta có thể biến khát vọng chuyển hóa thành một cuộc chạy trốn. Nếu quá sợ, ta có thể gọi sự mắc kẹt là ổn định. Vì vậy, điều quan trọng là đi từng bước có ý thức.</p><p>Đường Sao Tỏa Sáng là lời mời dành cho những người không muốn chỉ sống theo quán tính. Không ai ở đây cần trở thành một hình mẫu hoàn hảo. Điều cần hơn là khả năng nhìn lại, học sâu, nói thật, sáng tạo và xây dựng đời sống từ một trung tâm bền hơn.</p><p>Hôm nay, bạn không cần trả lời toàn bộ tương lai. Hãy chỉ hỏi: điều gì trong đời sống mình cần được giữ bằng lòng biết ơn, điều gì cần dừng bằng sự trung thực, và một bước nhỏ nào có thể giúp mình sống gần hơn với điều mình tin là đúng?</p>',
  '<p>Có rất nhiều người cảm thấy đời sống hiện tại không còn phù hợp với mình nữa. Họ vẫn làm những việc cần làm, vẫn giữ những vai trò quen thuộc, vẫn mỉm cười trong những cuộc gặp thường ngày. Nhưng bên trong có một cảm giác lặng lẽ rằng nếu cứ sống như cũ thêm nhiều năm nữa, điều gì đó quan trọng sẽ bị đánh mất.</p><p>Muốn sống khác không có nghĩa là ghét đời sống hiện tại. Nhiều khi đó là dấu hiệu của sự trưởng thành. Một phiên bản cũ từng giúp ta đi qua một giai đoạn, nhưng không nhất thiết đủ cho giai đoạn tiếp theo. Một công việc từng nuôi sống ta, một mối quan hệ từng nâng đỡ ta, một cách nghĩ từng bảo vệ ta, đến lúc nào đó có thể cần được nhìn lại.</p><p>Chân dung của người muốn sống khác thường không phải người bốc đồng. Họ có thể rất trách nhiệm, thậm chí quá trách nhiệm. Họ không muốn phá bỏ mọi thứ chỉ để thỏa mãn cảm xúc nhất thời. Họ chỉ cảm thấy cần một đời sống thật hơn: làm việc không phản bội giá trị, kết nối không đánh mất lòng tự trọng, phát triển không làm cạn kiệt sức khỏe, thành công không khiến mình xa lạ với chính mình.</p><p>Điểm bắt đầu thường không phải là đổi hết mọi thứ. Nó là phân biệt ba nhóm điều. Nhóm thứ nhất là điều cần giữ: những giá trị, con người, thói quen và trách nhiệm vẫn còn nuôi dưỡng mình. Nhóm thứ hai là điều cần dừng: những vòng lặp làm mình nhỏ lại, những cam kết không còn thật, những cách sống chỉ nhằm tránh sự phán xét. Nhóm thứ ba là điều cần thử: một thực hành nhỏ, một cuộc trò chuyện thật, một khoảng nghỉ, một dự án phụ, một cách học mới để kiểm chứng hướng đi.</p><p>Sống khác cần can đảm, nhưng cũng cần sự hiền lành với chính mình. Nếu quá vội, ta có thể biến khát vọng chuyển hóa thành một cuộc chạy trốn. Nếu quá sợ, ta có thể gọi sự mắc kẹt là ổn định. Vì vậy, điều quan trọng là đi từng bước có ý thức.</p><p>Đường Sao Tỏa Sáng là lời mời dành cho những người không muốn chỉ sống theo quán tính. Không ai ở đây cần trở thành một hình mẫu hoàn hảo. Điều cần hơn là khả năng nhìn lại, học sâu, nói thật, sáng tạo và xây dựng đời sống từ một trung tâm bền hơn.</p><p>Hôm nay, bạn không cần trả lời toàn bộ tương lai. Hãy chỉ hỏi: điều gì trong đời sống mình cần được giữ bằng lòng biết ơn, điều gì cần dừng bằng sự trung thực, và một bước nhỏ nào có thể giúp mình sống gần hơn với điều mình tin là đúng?</p>',
  '<p>The beginning is not changing everything at once, but seeing what must be kept, what must stop, and what small truthful step can be taken today.</p><p>Wanting to live differently does not mean hating your current life. Often it is a sign of growth. An older version of life may have helped you through one season without being enough for the next. A job, relationship, or way of thinking that once protected you may eventually need to be re-examined.</p><p>The person who wants to live differently is not always impulsive. Often they are deeply responsible. They do not want to destroy everything for a passing emotion; they want a truer life: work that does not betray values, connection that does not erase dignity, growth that does not drain health, success that does not make them a stranger to themselves.</p><p>Begin by naming what to keep, what to stop, and what to try. Đường Sao Tỏa Sáng is an invitation for those who do not want to live only by momentum. A different life may begin quietly, with one step that no longer betrays yourself.</p>',
  '', '', 'hành trình,định hướng', 1,
  '2026-01-22T08:00:00.000Z', '2026-06-07T10:30:00.000Z'
);
