#!/usr/bin/env bash
set -euo pipefail

BASE="${BASE_URL:-https://duongsaotoasang.com}"
BASE="${BASE%/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
UNKNOWN_PATH="/random-unknown-url-xyz-12345"
MISSING_CONTENT_PATH="/content?slug=missing-smoke-slug-404"

urls=(
  "/"
  "/about"
  "/program"
  "/posts"
  "/content?slug=impact-khong-phai-cau-chuyen-cam-dong"
  "/content?slug=star-journey-os-chi-mo-khi-nen-tang-du-san-sang"
  "/content?slug=90-ngay-dau-cua-thu-vien-tri-thuc-dsts"
  "/content?slug=tour-2026-2027-la-roadmap-khong-phai-lich-ban-ve"
  "/content?slug=press-kit-can-noi-ro-dieu-da-xac-minh"
  "/content?slug=partners-khong-phai-logo-de-trang-tri"
  "/content?slug=support-dsts-hoi-dung-noi-khong-gui-du-lieu-nhay-cam"
  "/content?slug=privacy-legal-disclosure-la-nen-mong-public-site"
  "/content?slug=nguoi-viet-muon-noi-bridge-khong-dan-vao-link-hong"
  "/content?slug=script-journey-khong-phai-goi-ban-hang"
  "/content?slug=event-readiness-no-owner-no-event"
  "/content?slug=diaspora-map-can-bao-ve-quyen-rieng-tu"
  "/content?slug=minh-bach-truoc-khi-gay-quy-dsts"
  "/content?slug=guardian-first-nguyen-tac-bao-ve-tre-em-ndnum"
  "/content?slug=nguoi-moi-nen-bat-dau-dsts-tu-dau"
  "/content?slug=ke-hoach-phat-trien-dsts-2026-2027"
  "/content?slug=nguyen-tac-public-site-khong-trang-den"
  "/content?slug=movement-portal-mo-an-toan-theo-tung-cong"
  "/content?slug=sang-tao-khong-bat-dau-tu-tham-vong"
  "/events"
  "/scripts"
  "/donate"
  "/transparency"
  "/legal"
  "/terms"
  "/refund"
  "/privacy"
  "/contact"
  "/payment-confirmation"
  "/dream-nurture"
  "/ndnum"
  "/movement"
  "/movement/sponsors"
  "/movement/events"
  "/movement/gala-2026"
  "/movement/diaspora-map"
  "/movement/press"
  "/movement/partners"
  "/movement/tour-2026-2027"
  "/scripts/rising-entrepreneur"
  "/scripts/global-artist"
  "/scripts/singing-icon"
  "/scripts/cinematic-actor"
  "/scripts/the-thinker"
  "/scripts/creative-leader"
  "/scripts/cultural-ambassador"
  "/scripts/dsts-legacy"
  "/scripts/global-story"
  "/sitemap.xml"
  "/rss.xml"
  "/robots.txt"
  "/og.png"
)

content_checks=(
  "/posts|THƯ VIỆN TRI THỨC"
  "/posts|data-dsts-ssr=\"posts\""
  "/posts|Impact không phải câu chuyện cảm động"
  "/posts|Tour 2026-2027 là roadmap"
  "/posts|Support DSTS"
  "/posts|Script Journey không phải gói bán hàng"
  "/posts|Minh bạch trước khi gây quỹ"
  "/posts|Kế hoạch phát triển Đường Sao Tỏa Sáng 2026-2027"
  "/posts|Khởi nghiệp từ nơi sống thật"
  "/posts|\"@type\":\"ItemList\""
  "/content?slug=impact-khong-phai-cau-chuyen-cam-dong|Impact không phải câu chuyện cảm động, mà là điều có thể kiểm chứng"
  "/content?slug=impact-khong-phai-cau-chuyen-cam-dong|Đo tác động mà không phơi bày con người"
  "/content?slug=star-journey-os-chi-mo-khi-nen-tang-du-san-sang|Star Journey OS chỉ nên mở khi nền tảng đủ sẵn sàng"
  "/content?slug=star-journey-os-chi-mo-khi-nen-tang-du-san-sang|Layer 2 cần nền trước khi cần giao diện"
  "/content?slug=90-ngay-dau-cua-thu-vien-tri-thuc-dsts|90 ngày đầu của thư viện tri thức DSTS cần giữ lời hứa gì"
  "/content?slug=90-ngay-dau-cua-thu-vien-tri-thuc-dsts|Fallback là lời hứa kỹ thuật của nội dung"
  "/content?slug=tour-2026-2027-la-roadmap-khong-phai-lich-ban-ve|Tour 2026-2027 là roadmap, không phải lịch bán vé"
  "/content?slug=tour-2026-2027-la-roadmap-khong-phai-lich-ban-ve|Roadmap giúp chuẩn bị, không thay thế vận hành"
  "/content?slug=press-kit-can-noi-ro-dieu-da-xac-minh|Press Kit cần nói rõ điều đã xác minh và điều chưa công bố"
  "/content?slug=press-kit-can-noi-ro-dieu-da-xac-minh|Verified facts trước, vision sau"
  "/content?slug=partners-khong-phai-logo-de-trang-tri|Partners không phải logo để trang trí, mà là trách nhiệm công bố"
  "/content?slug=partners-khong-phai-logo-de-trang-tri|Partner page cần trạng thái rõ"
  "/content?slug=support-dsts-hoi-dung-noi-khong-gui-du-lieu-nhay-cam|Support DSTS: hỏi đúng nơi, không gửi dữ liệu nhạy cảm"
  "/content?slug=support-dsts-hoi-dung-noi-khong-gui-du-lieu-nhay-cam|Support không thay thế legal hoặc child safety review"
  "/content?slug=privacy-legal-disclosure-la-nen-mong-public-site|Privacy và legal disclosure là nền móng của public site"
  "/content?slug=privacy-legal-disclosure-la-nen-mong-public-site|Privacy là thiết kế, không chỉ là văn bản"
  "/content?slug=nguoi-viet-muon-noi-bridge-khong-dan-vao-link-hong|Người Việt Muôn Nơi bridge: không dẫn người dùng vào link hỏng"
  "/content?slug=nguoi-viet-muon-noi-bridge-khong-dan-vao-link-hong|Không để homepage dẫn vào trải nghiệm hỏng"
  "/content?slug=script-journey-khong-phai-goi-ban-hang|Script Journey không phải gói bán hàng, mà là bản đồ phát triển cá nhân"
  "/content?slug=script-journey-khong-phai-goi-ban-hang|Đọc script như một gương soi"
  "/content?slug=event-readiness-no-owner-no-event|Event readiness: không có owner thì không có event"
  "/content?slug=event-readiness-no-owner-no-event|Báo cáo sau sự kiện là một phần của sự kiện"
  "/content?slug=diaspora-map-can-bao-ve-quyen-rieng-tu|Diaspora Map cần bảo vệ quyền riêng tư trước khi kể câu chuyện toàn cầu"
  "/content?slug=diaspora-map-can-bao-ve-quyen-rieng-tu|Bản đồ giai đoạn đầu nên là dữ liệu tổng hợp"
  "/content?slug=minh-bach-truoc-khi-gay-quy-dsts|Minh bạch trước khi gây quỹ: vì sao DSTS tạm đóng donate"
  "/content?slug=minh-bach-truoc-khi-gay-quy-dsts|Niềm tin phải đi trước dòng tiền"
  "/content?slug=guardian-first-nguyen-tac-bao-ve-tre-em-ndnum|Guardian-first: nguyên tắc bảo vệ trẻ em của NDNUM"
  "/content?slug=guardian-first-nguyen-tac-bao-ve-tre-em-ndnum|Không contact trực tiếp với trẻ em"
  "/content?slug=nguoi-moi-nen-bat-dau-dsts-tu-dau|Người mới nên bắt đầu với DSTS từ đâu"
  "/content?slug=nguoi-moi-nen-bat-dau-dsts-tu-dau|Đọc trang chủ để nắm hệ thống"
  "/content?slug=ke-hoach-phat-trien-dsts-2026-2027|Kế hoạch phát triển Đường Sao Tỏa Sáng 2026-2027"
  "/content?slug=ke-hoach-phat-trien-dsts-2026-2027|Movement Portal: mở từng cổng, không mở ồ ạt"
  "/content?slug=ke-hoach-phat-trien-dsts-2026-2027|data-dsts-ssr=\"content\""
  "/content?slug=nguyen-tac-public-site-khong-trang-den|Nguyên tắc public site không được có trang đen"
  "/content?slug=nguyen-tac-public-site-khong-trang-den|Smoke test là hợp đồng tối thiểu"
  "/content?slug=movement-portal-mo-an-toan-theo-tung-cong|Movement Portal mở an toàn theo từng cổng như thế nào"
  "/content?slug=movement-portal-mo-an-toan-theo-tung-cong|Release gates bảo vệ người dùng và team"
  "/content?slug=sang-tao-khong-bat-dau-tu-tham-vong|Sáng tạo không bắt đầu từ tham vọng"
  "/content?slug=sang-tao-khong-bat-dau-tu-tham-vong|data-dsts-ssr=\"content\""
  "/content?slug=sang-tao-khong-bat-dau-tu-tham-vong|\"@type\":\"BlogPosting\""
  "/events|DSTS Foundation Briefing"
  "/events|Thứ Bảy 20/06/2026"
  "/events|TP. Hồ Chí Minh + online hybrid"
  "/movement|Movement Portal"
  "/movement|data-dsts-surface=\"movement-home\""
  "/movement|Không mở sponsor inquiry"
  "/movement|Không thu email"
  "/movement/sponsors|data-dsts-surface=\"movement-sponsors\""
  "/movement/sponsors|Sponsor Readiness Hub"
  "/movement/sponsors|Không có sponsor inquiry form"
  "/movement/sponsors|13 gói tài trợ ở mức taxonomy"
  "/movement/events|data-dsts-surface=\"movement-events\""
  "/movement/events|Movement Events"
  "/movement/events|Không có event registration form"
  "/movement/events|NO OWNER = NO EVENT"
  "/movement/gala-2026|data-dsts-surface=\"movement-gala-status\""
  "/movement/gala-2026|Gala status pending Founder A7 confirm"
  "/movement/gala-2026|Không có gala registration form"
  "/movement/gala-2026|Founder TBD"
  "/movement/press|data-dsts-surface=\"movement-press\""
  "/movement/press|Press Kit DSTS"
  "/movement/press|Không có media contact form"
  "/movement/partners|data-dsts-surface=\"movement-partners\""
  "/movement/partners|DSTS Partners"
  "/movement/partners|Không có sponsor inquiry form"
  "/movement/tour-2026-2027|data-dsts-surface=\"movement-tour\""
  "/movement/tour-2026-2027|DSTS World Tour 2026-2027"
  "/movement/tour-2026-2027|Không có event registration form"
  "/movement/diaspora-map|data-dsts-surface=\"movement-diaspora-map\""
  "/movement/diaspora-map|DSTS Diaspora Map"
  "/movement/diaspora-map|Không thu dữ liệu cá nhân"
  "/movement/diaspora-map|k-anonymity"
  "/dream-nurture|Nuôi Dưỡng Những Ước Mơ"
  "/dream-nurture|Guardian-first"
  "/dream-nurture|Không xử lý payment"
  "/ndnum|Phase 0B"
  "/donate|Trạng thái: TẠM ĐÓNG"
  "/transparency|Báo cáo khởi tạo Q2/2026"
  "/legal|id=\"refund\""
  "/scripts/rising-entrepreneur|id=\"purchaseSafety\""
  "/scripts/rising-entrepreneur|Đánh giá minh họa"
  "/assets/app-v5.js|dsts-entity-disclosure"
)

failed=0

echo "=== DSTS Sprint 0 Smoke Test ==="
echo "Base: ${BASE}"
echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

node "${REPO_ROOT}/scripts/content-qa.mjs"
node "${REPO_ROOT}/scripts/api-surface-qa.mjs"
node "${REPO_ROOT}/scripts/link-qa.mjs"
echo ""

for path in "${urls[@]}"; do
  status="$(curl -o /dev/null -sS -L --max-redirs 5 --connect-timeout 8 --max-time 20 -w "%{http_code}" "${BASE}${path}")"
  if [[ "$status" == "200" ]]; then
    printf "PASS %s  %s\n" "$status" "$path"
  else
    printf "FAIL %s  %s\n" "$status" "$path"
    failed=$((failed + 1))
  fi
done

echo ""
echo "=== Content checks ==="
for check in "${content_checks[@]}"; do
  path="${check%%|*}"
  needle="${check#*|}"
  body="$(curl -sS -L --max-redirs 5 --connect-timeout 8 --max-time 20 "${BASE}${path}")"
  if grep -Fq "$needle" <<< "$body"; then
    printf "PASS content  %s  contains [%s]\n" "$path" "$needle"
  else
    printf "FAIL content  %s  missing [%s]\n" "$path" "$needle"
    failed=$((failed + 1))
  fi
done

echo ""
echo "=== 404 check ==="
status_404="$(curl -o /dev/null -sS --connect-timeout 8 --max-time 20 -w "%{http_code}" "${BASE}${UNKNOWN_PATH}")"
if [[ "$status_404" == "404" ]]; then
  printf "PASS 404  %s\n" "$UNKNOWN_PATH"
else
  printf "FAIL expected 404 for %s, got %s\n" "$UNKNOWN_PATH" "$status_404"
  failed=$((failed + 1))
fi

content_404="$(curl -o /dev/null -sS --connect-timeout 8 --max-time 20 -w "%{http_code}" "${BASE}${MISSING_CONTENT_PATH}")"
if [[ "$content_404" == "404" ]]; then
  printf "PASS content-404  %s\n" "$MISSING_CONTENT_PATH"
else
  printf "FAIL expected 404 for %s, got %s\n" "$MISSING_CONTENT_PATH" "$content_404"
  failed=$((failed + 1))
fi

echo ""
if [[ "$failed" -gt 0 ]]; then
  echo "FAILED: ${failed} smoke check(s) failed"
  exit 1
fi

echo "PASSED: all smoke checks passed"
